export const FETCH_PRICE_REQUEST = 'FETCH_PRICE_REQUEST';
export const FETCH_PRICE_SUCCESS = 'FETCH_PRICE_SUCCESS';
export const FETCH_PRICE_FAILURE = 'FETCH_PRICE_FAILURE';
export const SET_PURCHASE_AMOUNT = 'SET_PURCHASE_AMOUNT';
export const SET_QUOTE = 'SET_QUOTE';
export const SET_BTC_BALANCE = 'SET_BTC_BALANCE';
export const SET_USD_BALANCE = 'SET_USD_BALANCE';